---
- hosts: localhost
  gather_facts: yes

  vars_files:
    - vars.yml
  vars:
    cluster_name:
    test_case_name: "GKE_CREATE_CLUSTER"

  tasks:
    - block:
        - name: Generating Random Cluster Name
          shell: python ../../utils/name_generator/namesgenerator.py
          register: cluster_name
          when: not cluster_name

        - set_fact:
            cluster_name: "{{ cluster_name.stdout }}"
          when: cluster_name.stdout is defined

        - name: Generate SSH Keys 
          shell: yes y | ssh-keygen -t rsa -N "" -f $HOME/.ssh/{{ ssh_key_fn }} -C {{ ssh_user }}
          args:
            executable: /bin/bash
          no_log: True

        - name: Format SSH Key for GKE
          shell: sed -i '1s/^/{{ ssh_user }}:/' $HOME/.ssh/{{ ssh_key_fn }}.pub
          args:
            executable: /bin/bash

        - name: create GKE cluster
          gcp_container_cluster:
            name: "{{ cluster_name }}"
            initial_node_count: "{{ initial_node_count }}"
            monitoring_service: none
            logging_service: none
            node_config:
              machine_type: "{{ machine_type }}"
              disk_size_gb: "{{ disk_size_gb }}"
              image_type: "{{ image_type }}"
            zone: "{{ zone }}"
            project: "{{ project }}"
            auth_kind: "{{ auth_kind }}"
            scopes:
              - https://www.googleapis.com/auth/cloud-platform
            state: present

        - name: Save cluster info
          lineinfile:
            create: yes
            state: present
            path: "~/logs/clusters"
            line: "{{ cluster_name }}"

        - name: Get the kubeconfig and set kubectl for RBAC
          shell: gcloud container clusters get-credentials {{ cluster_name }} --zone={{ zone }}
          args:
            executable: /bin/bash
          no_log: True 

        - name: Set kubectl context to admin context
          shell: kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user={{user}}
          args:
            executable: /bin/bash
          no_log: True

        - name: Get Nodes
          shell: kubectl get nodes -o=custom-columns=NAME:.metadata.name --no-headers
          args:
            executable: /bin/bash
          register: node_names

        - name: Set SSH connections
          shell: gcloud compute instances add-metadata {{item}} --metadata-from-file ssh-keys=$HOME/.ssh/{{ ssh_key_fn }}.pub --zone={{ zone }}
          args:
            executable: /bin/bash
          loop: "{{ node_names.stdout_lines }}"
          no_log: True

        - name: Set Test Status
          set_fact:
            flag: "Test Passed"

      rescue:  
        - name: Set Test Status
          set_fact:
            flag: "Test Failed"
